<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlowBoard.Frontend.Services.Abstractions\FlowBoard.Frontend.Services.Abstractions.csproj" />
    <ProjectReference Include="..\FlowBoard.Frontend.Domain\FlowBoard.Frontend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.9" />
    <PackageReference Include="Refit.HttpClientFactory" Version="11.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
